export const state = {
  page: "direct",
  videos: [],
  vaultVideos: [],
  archiveVideos: [],
  selectedVideoId: "",
  researches: [],
  selectedResearchId: "",
  jobs: new Map(),
  selectedJobId: "",
  runtime: null,
  ws: null,
  wsReconnectTimer: null,
  jobsPollTimer: null,
  livePollTimer: null,
  directSaveProgress: new Map(),
  directResultContext: null,
  stackInfo: null,
  componentJobs: new Map(),
  selectedComponentJobId: "",
  componentPollTimer: null,
};
